name: CI/CD Pipeline

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt || true

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pytest
        run: pip install pytest

      - name: Run Tests
        run: pytest

      - name: Install flake8
        run: pip install flake8

      - name: Lint Code
        run: flake8 .

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploying app 🚀"
